steps:
# install npm packages
- name: 'gcr.io/cloud-builders/npm'
  id: Install
  args: ['install']

# builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hf-cloudbuild-ci:$SHORT_SHA'
  - '.'

# pushes the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/hf-cloudbuild-ci:$SHORT_SHA'
