apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: honestfood
  annotations:
    alpha/target.custom-metrics.podautoscaler.kubernetes.io: '{"items":[{"name":"qps", "value": "20"}]}'
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hf-nodejs-app
  metrics:
  - type: Pods
    pods:
      metricName: custom-metric
      targetAverageValue: 20
  
